name: passwordz
description: A new password manager app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^1.1.0
  flutter_secure_storage: ^6.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  font_awesome_flutter: ^10.3.0
  pine: ^1.0.1
  provider: ^6.0.5
  retrofit: ^3.3.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  auto_route: ^5.0.4
  favicon: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_password_strength: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  bloc_test: ^9.1.0
  retrofit_generator: ^4.2.0
  auto_route_generator: ^5.0.2
  http_mock_adapter: ^0.3.3
  data_fixture_dart: ^2.2.0
  mockito: ^5.3.2

flutter:
  generate: true
  uses-material-design: true
